version: '2'

services:
#    device-kiwi-prugw:
#        image: openkorp/opendlv-device-kiwi-prugw-multi:latest
#        network_mode: "host"
#        command: "/usr/bin//opendlv-device-kiwi-prugw --cid=111 --names=steering,propulsion --types=servo,esc --channels=1,2 --offsets=0,0 --maxvals=0.4,1"

    device-ps3controller:
        image: ps3:ps3v0
        network_mode: "host"
        devices:
          - "/dev/input/js1:/dev/input/js0"
        command: "/usr/bin/opendlv-device-ps3controller --cid=219 --cidpwm=222 --freq=50 --input=/dev/input/js0 --angleconversion=20 --verbose=1" 
